### ISSUE TITLE
Won't cast spell on @mouseover target

### ISSUE THREAD

**Issue by Rollo-Tomasi-git** [bhhandley/CleveRoidMacros#4]
This macro doesnt cast Taunt on my mouseover target:
/cast [stance:2 nocooldown:Taunt @mouseover] Taunt

This works as intended (taunts my mouseover target if I'm next to it - even if I have another target chosen in the UI)
/cast [stance:2 nocooldown:Taunt @mouseover]  {"/run CastSpellByName("Taunt","mouseover")"}

My guess is the add-on tries to target the normal target no matter if @mouseover is chosen? (Maybe it checks mouseover for the conditional, but then reverts to the normal target before actually casting the spell?)

**Comment by bhhandley** [comment]
Thanks for the report.  It's a known issue that happened while trying to deal with HealComm support.  I already have it resolved, just haven't released an update before I work out which way I want to apply the fix to try and not break HealComm or make things more complex than they need to be.  I'll shoot you a reply as soon as I push an update.

**Comment by bhhandley** [comment]
As a follow-up, I did push the update I mentioned.  If you use HealComm, please see the README for information.  That aside, I just now more closely read your macro -- unitsids, spell and item names, and most things are case sensitive.  Does it work with @mouseover instead of @mouseOver  ?

**Comment by Rollo-Tomasi-git** [comment]
Can confirm that it works as intended now. :-)  
(And yeah, github changes how '@'mouseover is displayed, as you noticed.)

**Comment by TreeLuna** [comment]
Hello! Sorry for necroing but I am also having this issue, did you roll back an update? I've got version 1.10, but am getting the error of "Invalid Target" when trying to cast Hunter's Mark on an enemy NPC, similar things seem to happen on my druid, with heals being targeted at myself or my target.

What I have currently for macro for Hunter's Mark is for testing:
#showtooltip
/cast [@mousover] Hunter's Mark; Hunter's Mark
